### ISSUE TITLE
When I install with docker, I need to map those ports

### ISSUE THREAD

**Issue by blue-cai** [TRON-US/go-btfs#1006]
When other hosts want to upload contracts to me, which ports do I need to map so that other hosts can connect to me.4001?5001?
So tell me how to configure port mapping when installing with docker.Thank you.

**Comment by istarion** [comment]
Hello, I use docker-compose bellow:

```
version: "3.9"
services:
  btfs:
    image: btfs_docker:v1.5.1
    ports:
      - "5001:5001"
      - "4001:4001"
    volumes:
      - type: bind
        source: /mnt/mirrored/btfs
        target: /data/btfs
    environment:
      - ENABLE_WALLET_REMOTE=true
    restart: unless-stopped
```
After the first start, you should execute the command  provided by GUI in your container (`docker exec -it BTFS_CONTAINER_NAME /bin/sh`)
I've also configured port forwarding to port 4001 on my router, and have white IP.

You should use the latest release version (v1.5.1) instead of the snapshot, to get the best host score. btfs_docker:v1.5.1 is my local docker image, use your own name.

But bad news, there is 1.8 PiB of data distributed among 230 PiB storage, so it is hard to get a contract today.
